<?php

include "includes/helpers/helpers.php";

?>
<?= createSiteStart($patterns['start']); ?>



<div class="authentication">
    <img src="/content/images/login-bg.jpg" class="bg">
</div>

<!-- Modal -->
<div id="modal-healthstream-id-create" class="modal show modal-external" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="branding">
                    <img src="/content/images/logo-healthstream-large.png" alt="HealthStream">
                </div>
            </div>
            <form data-toggle="validator" id="createIdForm" method="post" action="#">
                <div class="modal-body">
                    <h3 class="title">Create a HealthStream ID</h3>
                    <div class="form-group">
                        <label>First Name</label>
                        <input type="text" name="first_name" id="first_name" class="form-control  stored" placeholder="First Name" required>
                    </div>
                    <div class="form-group">
                        <label>Last Name</label>
                        <input type="text" name="last_name" id="last_name" class="form-control stored" placeholder="Last Name" required>
                    </div>
                    <div class="form-group">
                        <label>Personal Email Address</label>
                        <input type="email" name="email" id="email" class="form-control stored" placeholder="someone@gmail.com" required>
                    </div>
                    <div class="form-group">
                        <label>Confirm Personal Email Address</label>
                        <input type="email" name="confirmEmail" id="confirmEmail" class="form-control stored" placeholder="someone@gmail.com" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Retype Password</label>
                        <input type="password" name="confirmPassword" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label class="checkbox"><input type="checkbox" name="privacy" value="Yes" required> Yes, I've read the <a href="http://www.healthstream.com/privacy-statement" target="_blank">privacy policy</a> and agree to the <a href="#modal-termsconditions" data-toggle="modal">terms &amp; conditions</a></label>
                    </div>
                    <div class="form-group nav-buttons">
                        <button class="btn btn-success" type="submit">Create Account</button>
                    </div>
                    <div class="form-group">
                        <p class="small">Already have a HealthStream ID? <a href="healthstream-id-login.php">Log In</a></p>
                    </div>
                </div>

                <div class="modal-footer">
                    Copyright &copy; <?php echo date("Y") ?> HealthStream, Inc. All Rights Reserved.
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal modal-lg fade" id="modal-termsconditions" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                <h4 class="modal-title">Terms &amp; Conditions</h4>
            </div>
            <div class="modal-body" style="font-size:12px;">
                <p>
                    <strong>IMPORTANT:</strong>  These Terms of Use (“<strong>TOU</strong>”) is a legal agreement between You (an individual person, who will be referred to in this TOU as “<strong>You</strong>” or “<strong>End User</strong>”) and <strong>HealthStream, Inc.</strong> (referred to in this TOU as “<strong>Company</strong>”) for the Services that accompany this TOU, which may include associated printed and/or electronic documentation. <strong>BY ACCESSING THE SERVICES, YOU AGREE TO BE BOUND BY ALL TERMS OF THIS TOU. PLEASE READ THEM CAREFULLY. IT PROVIDES A LICENSE TO USE THE SERVICES AND CONTAINS WARRANTY INFORMATION AND LIABILITY DISCLAIMERS</strong>.
                </p>

                <ol type="1"  class="tc-list">
                    <li>
                        <p><u>Definitions.</u></p>

                        <p>“End User Data” means all data or information submitted or generated by You or obtained from You as a result of Your use of the Services, including without limitation biographical and demographic information and data about You, Your educational background, Your employment history, and Your taking and/or completing continuing education courses.</p>

                        <p><u>“Services”</u> means all of the Company’s services which you are accessing and/or receiving from the Company either via your employer or on your own, or which the Company otherwise provides. </p>
                    </li>
                    <li>
                        <p><u>Services.</u></p>


                        <ol type="a">
                            <li>
                                <i>License</i>

                                <ol type="i">
                                    <li>
                                        <p>Company shall make the Services available to You pursuant to the terms of this TOU.   In exchange for Your agreement to this TOU, Company hereby grants to You a limited, revocable, non-exclusive, non-transferable license to access and use the Services.  You acknowledge that information, materials, products, and/or Third-Party Content made available through the Services are subject to change at any time and without notice.</p>
                                    </li>
                                    <li>
                                        <p>All End User Data is owned exclusively by You. In exchange for Company’s making the Services available to You pursuant to the terms of this TOU, You hereby grant the Company an unrestricted, royalty-free, irrevocable license (i) to maintain, distribute, and make available your End User Data to Your current or potential employer(s), healthcare providers who may contract for your services, and accreditation or licensing organizations; (ii) to maintain, distribute, and use aggregate compilations of End User Data; (iii) to fulfill and manage purchases of the Services; (iv) to provide you with information related to other Company Services that may be of interest to you; (v) to provide, maintain, protect and improve the Services (including the development of new Services).</p>
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <p><i class="shimmed">User ID. </i>  Except with the prior written consent of Company, access to the Services are limited solely to You.  You accept responsibility for all activity that occurs under your account and password. You will either be assigned a unique account name and password by Company or your employer or be asked to create your own username and password for access to and use of the Services (“<strong>User ID</strong>”). Your User ID is for your personal use only and shall not, under any circumstances, be shared, distributed, or otherwise made available to any person or entity. You may not use false identities or impersonate any other person, or use a User ID that You are not authorized to use. You shall be solely responsible for ensuring the security and confidentiality of his/her User ID.  You acknowledge that he/she will be fully responsible for any and all liability incurred through use of his/her User ID and that any use of the Services under the User ID will be deemed to have been performed by You.  Company shall have no responsibility for the consequences of unauthorized access to the Services that arise from unauthorized disclosure of a User ID or password issued to or on behalf of You.  You shall notify Company immediately of any suspected theft, loss or fraudulent use of Your User ID or password.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">End User Responsibilities.</i>  Under the terms of this TOU, You shall not, and shall not permit any third party to:  </p>

                                <ol type="i">
                                    <li>
                                        <p>Transfer Your license to use the Services or sublicense or assign Your license or rights under it;</p>
                                    </li>
                                    <li>
                                        <p>Use, download, copy, or transfer the Services or parts of the Services except as expressly permitted under this TOU;</p>
                                    </li>
                                    <li>
                                        <p>Distribute, rent, sell, loan, lease, sublicense or otherwise deal in the Services and/or any elements of the Services;</p>
                                    </li>
                                    <li>
                                        <p>Alter, adapt, merge, modify, translate, or create derivative works of the Services or any elements of the Services in any way, or for any purpose, other than with the prior written consent of Company;</p>
                                    </li>
                                    <li>
                                        <p>Reverse engineer, disassemble, or de-compile the Services or otherwise attempt to obtain or perceive the source code for the Services; </p>
                                    </li>
                                    <li>
                                        <p>Remove, change, or obscure any identification marks or notices of proprietary rights and restrictions in the Services or any elements of the Services; </p>
                                    </li>
                                    <li>
                                        <p>Enable any timesharing or services bureau use of the Services to or on behalf of any third party; </p>
                                    </li>
                                    <li>
                                        <p>Use the Services to defame, abuse, harass, threaten, or otherwise violate the legal rights of others, including others’ privacy rights;</p>
                                    </li>
                                    <li>
                                        <p>Use the Services in any manner that could damage, disable, overburden or impair any Company network or server or for any unlawful or unauthorized purpose;</p>
                                    </li>
                                    <li>
                                        <p>Attempt to gain unauthorized access to other accounts, computer systems or networks connected to any Company server or to any of the Services through hacking, password mining or any other means; </p>
                                    </li>
                                    <li>
                                        <p>Remove any copyright, trademark or other proprietary rights notice from the Services or materials or documentation within the Services; or </p>
                                    </li>
                                    <li>
                                        <p>Redistribute, copy, reproduce or disseminate to any person any information or content (except for content created by and about you for your personal use), including without limitation the Third-Party Content, without Company’s prior written consent.</p>
                                    </li>
                                </ol>
                            </li>
                            <li>
                                <p><i class="shimmed">Ownership.</i>  The Services are proprietary to Company and/or its licensors. The Services are licensed pursuant to the terms of this TOU and not sold. All rights, title and interest in and to the Services and all copyright, trade secret rights, patents, trademarks and any other intellectual property or proprietary rights in and to the Services shall at all times remain the exclusive property of Company and/or its licensors. All rights not expressly granted under this TOU are reserved by Company.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">Certain Third-Party Terms.</i>  The Services may include content that may be supplied by companies that are not affiliated with Company (“<strong>Third-Party Content</strong>”). Third-Party Content may be available through several locations in the Services, including without limitation, framed areas, through hyperlinks to third-party websites, or published or provided through the Services. The Third-Party Content may be protected by copyright or other intellectual property laws. YOU ACKNOWLEDGE AND AGREE THAT THIS TOU ONLY GOVERNS YOUR RELATIONSHIP WITH COMPANY, AND UNLESS EXPRESSLY SET FORTH HEREIN, DOES NOT AFFECT YOUR LEGAL RELATIONSHIP WITH ANY SUCH THIRD-PARTY CONTENT PROVIDERS. YOU UNDERSTAND AND AGREE THAT COMPANY PROVIDES NO WARRANTIES OF ANY KIND WITH REGARD TO THIRD-PARTY CONTENT, AND THAT YOU BEAR ALL RISK ASSOCIATED WITH USE OF OR RELIANCE UPON  THIRD-PARTY CONTENT. </p>
                            </li>
                            <li>
                                <p>
                                    <i class="shimmed">Documentation.</i> Any documentation that accompanies the Services, whether in printed, electronic, or any other form, is subject to the license set forth in Section 2(a), and is subject to all of the terms of this TOU.
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="shimmed">Availability.</i> The Services are available to anyone with Internet access.  However, the Services may not be continuously available due to maintenance or repairs or due to computer problems or crashes, disruption in Internet service or other unforeseen circumstances.  Further, a reference to a product or service on or in the Services does not imply that such product or service is or will be available in Your location.  The content of the Services are intended for use and display only where its use and display are permissible in accordance with applicable laws and regulations.
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="shimmed">Feedback.</i> Company may provide You with a mechanism to provide feedback, suggestions, and ideas about the Services (“<strong>Feedback</strong>”) if You choose. You agree that Company may, in its sole discretion, use the Feedback that You provide to Company in any way, including in future modifications of the Services or in other Company products or services. You hereby grant Company a perpetual, worldwide, fully transferable, irrevocable, royalty-free license to use, modify, create derivative works from, distribute, and display any information You provide to Company in the Feedback.
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="shimmed">Interactive Areas.</i> Company may provide interactive forums, chat rooms, bulletin boards and other interactive areas (collectively “<strong>Interactive Areas</strong>”) on or in the Services. If You use any of the Interactive Areas, You are solely responsible for Your own communications and the consequences of posting those communications. Company does not assume any responsibility for the truthfulness, accuracy or reliability of any material posted in any Interactive Area, or of consequences of any Interactive Area communications on or arising from use of the Services.
                                </p>
                            </li>
                        </ol>

                    <li>
                        <p><u>Termination.</u></p>

                        <ol type="a">
                            <li>
                                <p><i class="shimmed">Termination.</i>  This TOU and the license granted hereunder will terminate automatically if You are no longer eligible to receive the Services. Further, this TOU and the license granted hereunder may be terminated by Company at any time if You fail to comply with any terms of this TOU.  </p>
                            </li>
                            <li>
                                <p><i class="shimmed">Survival.</i>  Notwithstanding any termination of this TOU, the following provisions shall survive: Sections 2(d), 4, 5, 6, and 7.</p>
                            </li>
                        </ol>
                    </li>

                    <li>
                        <p><u>Disclaimer of Warranties.</u></p>

                        <ol type="a">
                            <li>
                                <p><i class="shimmed">Disclaimer.</i>  COMPANY IS PROVIDING THE SERVICES TO YOU "AS IS." COMPANY AND COMPANY’S LICENSORS MAKE NO WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY REGARDING OR RELATING TO THE SERVICES.  COMPANY EXPRESSLY AND SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, RESULTS, AND NONINFRINGEMENT WITH RESPECT TO THE SERVICES AND WITH RESPECT TO THE USE OF THE SERVICES. COMPANY MAKES NO WARRANTY, AND EXPRESSLY DISCLAIMS ANY OBLIGATION, THAT: (I) THE SERVICES OR ANY THIRD-PARTY CONTENT WILL MEET YOUR REQUIREMENTS OR WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; (II) THE CONTENT OF THE SERVICES OR THE THIRD-PARTY CONTENT WILL BE UP-TO-DATE, COMPLETE, COMPREHENSIVE, OR ACCURATE; (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES OR THE THIRD-PARTY CONTENT WILL BE ACCURATE OR RELIABLE;  (IV) THE QUALITY OF THE SERVICES OR ANY THIRD-PARTY CONTENT, INFORMATION, OR OTHER MATERIAL OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS; OR (V) THAT DEFECTS, IF ANY, WILL BE CORRECTED.</p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        <p><u>Limitation of Liability</u></p>

                        <p>NOTWITHSTANDING ANY DAMAGES THAT YOU MAY INCUR FOR ANY REASON WHATSOEVER (INCLUDING, WITHOUT LIMITATION, ALL DAMAGES REFERENCED HEREIN, AND ALL DIRECT OR GENERAL DAMAGES ARISING OUT OF CONTRACT, NEGLIENCE, OR ANY OTHER LEGAL OR EQUITABLE THEORY), THE ENTIRE LIABILITY OF COMPANY AND ANY OF ITS LICENSORS UNDER ANY PROVISION OF THIS TOU AND YOUR EXCLUSIVE REMEDY HEREUNDER SHALL BE LIMITED TO ONE HUNDRED DOLLARS ($100.00). TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY SHALL NOT BE LIABLE, UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY FOR ANY OF THE FOLLOWING, HOWEVER CAUSED AND WHETHER ARISING UNDER CONTRACT, TORT, OR OTHERWISE:</p>

                        <ol type="A">
                            <li>
                                <p>LOSS OF USE;</p>
                            </li>
                            <li>
                                <p>LOSS OR DAMAGE TO OR CORRUPTION OF DATA;</p>
                            </li>
                            <li>
                                <p>THE UNAUTHORIZED DISCLOSURE OF SENSITIVE, VALUABLE, OR CONFIDENTIAL INFORMATION;</p>
                            </li>
                            <li>
                                <p>LOSS ATTRIBUTABLE TO YOUR FAILURE TO MAKE AND RETAIN REASONABLE BACK-UPS OF YOUR DATA;  AND</p>
                            </li>
                            <li>
                                <p>ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES ARISING FROM THE SERVICES, AND/OR ANY THIRD-PARTY CONTENT.</p>
                            </li>
                        </ol>

                        <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO END USER. IF ANY EXCLUSION, DISCLAIMER OR OTHER PROVISION CONTAINED IN THIS TOU IS HELD TO BE INVALID FOR ANY REASON BY A COURT OF COMPETENT JURISDICTION AND COMPANY BECOMES LIABLE THEREBY FOR LOSS OR DAMAGE THAT COULD OTHERWISE BE LIMITED, SUCH LIABILITY WHETHER IN CONTRACT, TORT OR OTHERWISE, WILL NOT EXCEED THE AMOUNT ACTUALLY PAID FOR END USER’S USE OF THE SERVICES.</p>
                    </li>
                    <li>
                        <p><u>Indemnification.</u></p>

                        <p>You shall defend, indemnify and hold Company and its officers, directors, employees, licensors, representatives and/or agents harmless at all times from and against any and all claims, demands, actions, proceedings, damages, losses, liabilities, costs, and/or expenses (including without limitation, reasonable attorneys’ fees) in connection with or as a result of any claim that arises from any breach of this TOU by You.  Company will provide You with prompt written notice of any such claim, demand, action or proceeding to which the foregoing indemnity relates, and Company will have the right to participate in the defense thereof at Company’s expense.  </p>
                    </li>
                    <li>
                        <p><u>Miscellaneous.</u></p>

                        <ol type="a">
                            <li>
                                <p><i class="shimmed">Modification.</i> Company reserves the right to make changes to this TOU at any time, and such changes will be effective immediately upon posting to the Services. You should look at this TOU regularly. Your continued use of the Services will indicate your acceptance of the current TOU. </p>
                            </li>
                            <li>
                                <p><i class="shimmed">Severability.</i>  If a court of competent jurisdiction finds any provision of this TOU invalid or unenforceable, that provision of the TOU will be amended to achieve as nearly as possible the intent of the parties, and the remainder of this TOU will remain in full force and effect.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">Governing Law; Venue.</i> This TOU shall be construed and interpreted in accordance with the domestic laws of the state of Tennessee, excluding any choice of law rules. Unless the parties agree in writing to mediate or arbitrate a dispute, all disputes arising out of this TOU will be subject to the sole and exclusive jurisdiction of the state and federal courts with applicable jurisdiction located in Nashville, Tennessee, and each Party hereby consents to the personal jurisdiction thereof. EACH PARTY HEREBY WAIVES ANY RIGHT TO TRIAL BY JURY WITH RESPECT TO ANY DISPUTE, SUIT, ACTION OR PROCEEDING ARISING OUT OF OR RELATING TO THIS TOU OR OTHERWISE RELATING TO THE RELATIONSHIP OF THE PARTIES, WHETHER IN CONTRACT, TORT OR OTHERWISE.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">No Waiver.</i> No provision of this TOU shall be waived except pursuant to a writing executed by the party against whom the waiver is sought. The failure of Company to enforce at any time the provisions of this TOU shall in no way constitute a present or future waiver of such provisions, nor shall it in any way affect the right of Company to enforce each and every such provision thereafter.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">No Assignment.</i> You may not sell, assign, sublicense, encumber or otherwise transfer this TOU, the license granted hereunder, or any rights in and to any of the foregoing, directly or indirectly. Any attempt by You to assign its rights or obligations under this TOU in violation of this Section shall be void and of no effect.  Company may assign its interests under this TOU without notice to You. This TOU shall be binding upon and inure to the benefit of Company and You and their successors and permitted assigns.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">No Third Party Beneficiary.</i> This TOU controls the relationship between Company and You related to your use of the Services. It does not create any third party beneficiary rights. </p>
                            </li>
                            <li>
                                <p><i class="shimmed">Limitation of Claims.</i> Any claim or cause of action arising out of Your use of the Services or this TOU must be filed within one year after such claim or cause of action arose or it shall forever be barred, notwithstanding any statute of limitations or other law to the contrary. Within this period, any failure by Company to enforce or exercise any provision of this TOU or related right shall not constitute a waiver of that right or provision.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">Export Controls.</i>  The Services provided in connection with this TOU is for use in the United States only, unless Your employer and Company have expressly agreed otherwise.  You will not export, access, or send the Services or any software provided therein or any portion or aspect thereof to any other country or territory.</p>
                            </li>
                            <li>
                                <p><i class="shimmed">Entire Agreement.</i>  With respect to the subject matter hereof, this TOU contains the entire agreement between the parties, and this TOU supersedes all prior written and oral and all contemporaneous oral agreements and understandings between Company and You.  </p>
                            </li>
                        </ol>
                    </li>
                </ol>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<?= createPrototypeNav(); ?>
<?= createSiteScripts(); ?>
<script>
    $(function() {

        // PROTOTYPE: FORM VALIDATION
        $('#createIdForm').formValidation({
            framework: 'bootstrap',
            fields: {
                first_name: {
                    validators: {
                        notEmpty: {
                            message: 'First name is required'
                        },
                    }
                },
                last_name: {
                    validators: {
                        notEmpty: {
                            message: 'Last name is required'
                        },
                    }
                },
                email: {
                    validators: {
                        notEmpty: {
                            message: 'Email is required'
                        },
                        emailAddress: {
                            message: 'The input is not a valid email address'
                        }
                    }
                },
                confirmEmail: {
                    validators: {
                        notEmpty: {
                            message: 'Confirmation Email is required'
                        },
                        emailAddress: {
                            message: 'The input is not a valid email address'
                        },
                        identical: {
                            field: 'email',
                            message: 'The email address and its confirm are not the same'
                        }
                    }
                },
                confirmPassword: {
                    validators: {
                        identical: {
                            field: 'password',
                            message: 'The password and its confirm are not the same'
                        }
                    }
                },
                privacy: {
                    validators: {
                        notEmpty: {
                            message: 'Must be selected'
                        },
                    }
                },
            }
        });
    });


</script>

<?= createSiteEnd(); ?>